# Generated by Django 3.0.5 on 2020-04-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_date',
            new_name='date',
        ),
    ]
